# Generated by Django 2.2.3 on 2019-07-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='paradigm',
        ),
        migrations.AddField(
            model_name='language',
            name='email',
            field=models.EmailField(default='doe@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='language',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='language',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
