# Generated by Django 2.2.1 on 2019-08-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190806_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Buyer'),
        ),
    ]
